# Generated by Django 4.2.10 on 2024-02-12 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=99999999999)),
            ],
        ),
        migrations.CreateModel(
            name='SecondModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=99999999999)),
                ('flag', models.BooleanField()),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_model', to='app.firstmodel')),
            ],
        ),
    ]
